[build]
builder = "nixpacks"
buildCommand = "npm install && npm install express stripe && cd web && npm install && npm run build"
cleanCache = true

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckInterval = 10
