// Deterministic tarot card from birthdays + today (22 Major Arcana)
type L = Record<string, string>;

export interface TarotCard {
  id: number;
  name: string;
  meaning: string;
  emoji: string;
  orientation: string; // e.g. " (Ngược)" for Vietnamese reversed
}

const CARDS: { id: number; emoji: string; name: L; meaning: L }[] = [
  {id:0, emoji:'🌟', name:{zh:'愚人',en:'The Fool',es:'El Loco',fr:'Le Fou',th:'คนโง่ประหลาด',vi:'Chàng Khờ'}, meaning:{
    zh:'踏上未知旅程的勇气，新可能的开启。在感情中，这意味着愿意为爱冒险、放下算计、凭直觉前行——哪怕前路无人走过。逆位时，这张牌提醒你：莫让恐惧浇灭心中那团无畏之火，真正的亲密需要一颗赤子之心。当你犹豫是否该迈出那一步时，请记住，每一次真心跳跃都值得被宇宙接住。',
    en:'The courage to embark on an unknown journey — new possibilities await. In love, this means daring to leap without a safety net, trusting intuition over calculation. Reversed, it warns that fear is dampening your spark; true intimacy requires the heart of a child. When you hesitate at the edge, remember: every genuine leap of faith is worth taking.',
    es:'El valor para emprender un viaje desconocido — nuevas posibilidades le esperan. En el amor, esto significa atreverse a saltar sin red, confiando en la intuición por encima del cálculo. Invertido, advierte que el miedo está apagando tu chispa; la verdadera intimidad requiere un corazón de niño. Cuando dudas al borde, recuerda: cada salto genuino de fe vale la pena.',
    fr:'Le courage de partir vers l\'inconnu — de nouvelles possibilités vous attendent. En amour, cela signifie oser sauter sans filet, en faisant confiance à votre intuition plutôt qu\'au calcul. Inversé, il avertit que la peur étouffe votre flamme ; l\'intimité véritable exige le cœur d\'un enfant. Quand vous hésitez au bord, rappelez-vous : chaque saut de foi sincère mérite d\'être fait.',
    th:'ความกล้าที่จะเริ่มต้นการเดินทางแห่งความลึกลับ — โอกาสใหม่รอคุณอยู่ ในความรัก นี่หมายถึงการกล้ากระโดดโดยไม่มีเชือกยึด ไว้วางใจในสัญชาตญาณมากกว่าการคำนวณ เมื่ออยู่ในตำแหน่งกลับด้าน มันเตือนว่าความกลัวกำลังดับไฟในใจคุณ ความใกล้ชิดแท้จริงต้องการหัวใจของเด็ก เมื่อคุณลังเลที่ขอบนั้น จงจำไว้: การกระโดดด้วยความเชื่อทุกครั้งล้วนมีค่า',
    vi:'Can đảm bước vào hành trình chưa biết — những khả năng mới đang chờ đợi bạn. Trong tình yêu, đây là lời nhắc nhở rằng đôi khi ta cần buông bỏ tính toán và tin vào trực giác của trái tim, dám mạo hiểm vì yêu thương dù chưa ai từng đi qua con đường ấy. Nếu lá bài xuất hiện ngược, hãy cẩn thận — đừng để nỗi sợ dập tắt ngọn lửa can đảm trong bạn, bởi sự gần gũi đích thực cần một trái tim ngây thơ và chân thành. Khi bạn chần chừ trước bước ngoặt, xin nhớ rằng mọi bước nhảy chân thành đều đáng để vũ trụ đón nhận.'
  }},
  {id:1, emoji:'🔮', name:{zh:'魔术师',en:'The Magician',es:'El Mago',fr:'Le Bateleur',th:'นักมายกล',vi:'Nhà Ảo Thuật'}, meaning:{
    zh:'意志与行动力觉醒，创造显化的时刻。你的感情中出现这张牌，暗示着将心意化为现实的力量正在苏醒——你们有能力将关系塑造成心中所愿。逆位时，提醒你勿让才华沉睡，敢于行动才是破解困局的关键。手中的每一张牌都是你的资源，只看你愿不愿将它们翻出，将爱的可能性变为不可逆的现实。',
    en:'Manifestation and creation — willpower awakened into action. When this card appears in your relationship, the power to shape your bond is awakening — you have everything needed to make it what you desire. Reversed, it warns against letting potential gather dust; bold action is the key to breaking deadlocks. Every tool is already in your hands — the question is whether you dare turn intention into irreversible reality.',
    es:'Manifestación y creación — la fuerza de voluntad se despierta en acción. Cuando esta carta aparece en su relación, el poder de dar forma a su vínculo se está despertando — tiene todo lo necesario para convertirlo en lo que desea. Invertido, advierte contra dejar que el potencial se acumule en polvo; la acción audaz es la clave para romper los puntos muertos. Cada herramienta ya está en sus manos — la pregunta es si se atreve a convertir la intención en realidad irreversible.',
    fr:'Manifestation et création — la volonté s\'éveille en action. Quand cette carte apparaît dans votre relation, le pouvoir de façonner votre lien s\'éveille — vous avez tout ce qu\'il faut pour en faire ce que vous désirez. Inversé, il avertit de ne pas laisser le potentiel s\'ensabler ; l\'action audacieuse est la clé pour briser les blocages. Chaque outil est déjà entre vos mains — la question est de savoir si vous osez transformer l\'intention en réalité irréversible.',
    th:'การสร้างสรรค์และการแสดงออก — พลังจิตตื่นขึ้นสู่การลงมือ เมื่อไพ่นี้ปรากฏในความสัมพันธ์ของคุณ พลังในการสร้างสรรค์ความผูกพันกำลังตื่นขึ้น — คุณมีทุกสิ่งที่จำเป็นที่จะทำให้มันเป็นอย่างที่คุณปรารถนา เมื่อกลับด้าน มันเตือนว่าอย่าปล่อยให้ศักยภาพจมอยู่ในฝุ่น การลงมืออย่างกล้าหาญคือกุญแจในการทลายทางตัน ทุกเครื่องมืออยู่ในมือคุณแล้ว — คำถามคือคุณกล้าจะเปลี่ยนความตั้งใจเป็นความจริงที่หยุดยั้งไม่ได้หรือไม่',
    vi:'Hiện thực hóa và sáng tạo — ý chí thức tỉnh thành hành động. Trong tình yêu, lá bài này cho thấy bạn có khả năng biến ước mơ thành hiện thực, dùng sự sáng tạo và ý chí mạnh mẽ để kiến tạo mối quan hệ như mong muốn. Đừng chờ đợi phép màu từ bên ngoài — chính bạn là người cầm bút viết câu chuyện tình ấy. Nếu xuất hiện ngược, hãy chú ý đến sự do dự hoặc thiếu tập trung, đừng để tiềm năng của bạn bị lãng phí. Mọi công cụ đều nằm trong tay bạn — câu hỏi duy nhất là bạn có dám biến ý định thành hiện thực không thể đảo ngược.'
  }},
  {id:2, emoji:'🌙', name:{zh:'女祭司',en:'The High Priestess',es:'La Sacerdotisa',fr:'La Papesse',th:'นางพราหมณี',vi:'Nữ Đại Tư Tế'}, meaning:{
    zh:'直觉与秘密，等待揭晓的答案。这张牌暗示你的感情正处于一个需要信任直觉的阶段——有些事情尚未显现，但答案早已存在于内心深处。逆位时，提醒你倾听内心的声音，勿被表象所迷惑，真相需要时间慢慢浮出水面。在亲密关系中，沉默有时比千言万语更能传递灵魂的密码——学会在未知中安然等待。',
    en:'Intuition and mystery — the answer waits to be revealed. This card suggests your relationship is in a phase that demands trust in intuition — not everything is visible yet, but the answer already lives deep within. Reversed, it reminds you to listen to your inner voice and not be deceived by appearances; truth surfaces in its own time. In intimacy, silence sometimes speaks louder than a thousand words — learn to rest in the unknown.',
    es:'Intuición y misterio — la respuesta espera ser revelada. Esta carta sugiere que su relación está en una fase que exige confianza en la intuición — no todo es visible aún, pero la respuesta ya vive en lo profundo. Invertida, le recuerda escuchar su voz interior y no dejarse engañar por las apariencias; la verdad aflora a su debido tiempo. En la intimidad, el silencio a veces habla más que mil palabras — aprenda a descansar en lo desconocido.',
    fr:'Intuition et mystère — la réponse attend d\'être révélée. Cette carte suggère que votre relation traverse une phase exigeant confiance en l\'intuition — tout n\'est pas encore visible, mais la réponse habite déjà au plus profond. Inversé, elle vous rappelle d\'écouter votre voix intérieure et de ne pas vous laisser tromper par les apparences ; la vérité émerge en son temps. Dans l\'intimité, le silence parle parfois plus fort que mille mots — apprenez à vous reposer dans l\'inconnu.',
    th:'สัญชาตญาณและความลับ — คำตอบรอให้ถูกเปิดเผย ไพ่นี้บอกว่าความสัมพันธ์ของคุณอยู่ในช่วงที่ต้องไว้วางใจในสัญชาตญาณ — ยังมีสิ่งมากมายที่มองไม่เห็น แต่คำตอบอยู่ในดวงใจลึกๆ แล้ว เมื่อกลับด้าน มันเตือนให้ฟังเสียงภายในและอย่าหลงเชื่อภาพลวง ความจริงจะปรากฏเองในเวลาของมัน ในความใกล้ชิด ความเงียบบางครั้งพูดได้ดีกว่าพันคำ — จงเรียนรู้ที่จะอยู่กับความไม่รู้อย่างสงบ',
    vi:'Trực giác và bí ẩn — câu trả lời đang chờ được bật mí. Trong tình yêu, lá bài này cho thấy mối quan hệ đang ở giai đoạn cần sự thấu hiểu sâu sắc, đôi khi cần lắng nghe trực giác thay vì vội vàng kết luận. Những gì chưa lộ diện không phải là không tồn tại — câu trả lời đã an nghỉ sâu trong lòng bạn từ lâu rồi. Nếu xuất hiện ngược, hãy cẩn thận với những bí mật hoặc sự thiếu minh bạch, đừng để bề ngoài đánh lừa bạn. Trong sự gần gũi, đôi khi im lặng truyền tải nhiều hơn nghìn lời nói — hãy học cách bình thản chờ đợi trong bóng tối.'
  }},
  {id:3, emoji:'🌺', name:{zh:'女皇',en:'The Empress',es:'La Emperatriz',fr:'L\'Impératrice',th:'จักรพรรดินี',vi:'Nữ Hoàng'}, meaning:{
    zh:'丰盛与滋养，爱的温柔绽放。在感情中，这张牌象征着被爱环绕、安全感十足的状态——你们的关系正在经历一个自然的生长与绽放阶段。逆位时，提醒你关注自己的情感需求，勿忘自我滋养，只有先学会爱自己，才能更好地爱对方。爱如花园，需要悉心浇灌才能长出不凋的花——你既是被爱浇灌的那朵，也是握着水壶的园丁。',
    en:'Abundance and nurturing — love blooms gently. This card symbolizes being wrapped in love and safety — your relationship is going through a phase of natural growth and flowering. Reversed, it reminds you to tend to your own emotional needs first; only by loving yourself can you truly love another. Love is a garden — it needs patient tending to bloom without fading. You are both the flower being watered and the hand that holds the watering can.',
    es:'Abundancia y cuidado — el amor florece suavemente. Esta carta simboliza estar envuelto en amor y seguridad — su relación atraviesa una fase de crecimiento natural y florecimiento. Invertida, le recuerda atender sus propias necesidades emocionales primero; solo amándose a sí mismo puede amar verdaderamente a otro. El amor es un jardín que necesita cuidados pacientes para florecer sin marchitarse. Usted es tanto la flor regada como la mano que sostiene la regadera.',
    fr:'Abondance et tendresse — l\'amour fleurit doucement. Cette carte symbolise l\'amour et la sécurité qui vous enveloppent — votre relation traverse une phase de croissance et d\'épanouissement naturels. Inversé, elle vous rappelle de prendre soin de vos propres besoins émotionnels ; on ne peut vraiment aimer l\'autre qu\'en s\'aimant soi-même. L\'amour est un jardin qui demande des soins patients pour fleurir sans se faner. Vous êtes à la fois la fleur arrosée et la main qui tient l\'arrosoir.',
    th:'ความอุดมสมบูรณ์และการเอื้ออาทร — ความรักเบ่งบานอย่างอ่อนโยน ไพ่นี้สื่อถึงการได้ล้อมรอบด้วยความรักและความปลอดภัย — ความสัมพันธ์ของคุณกำลังผ่านช่วงเติบโตและเบ่งบานตามธรรมชาติ เมื่อกลับด้าน มันเตือนให้คุณดูแลความต้องการทางอารมณ์ของตัวเองก่อน เพราะต้องรักตัวเองจริงๆ จึงจะรักคนอื่นได้อย่างแท้จริง ความรักเป็นสวนที่ต้องดูแลด้วยความอดทนจึงจะผลิบานไม่โทรม คุณทั้งดอกไม้ที่ถูกรดน้ำและมือที่ถือกรวยรดน้ำ',
    vi:'Phồn vinh và nuôi dưỡng — tình yêu nở rộ nhẹ nhàng. Đây là thời kỳ mà mối quan hệ được nuôi dưỡng bởi sự chăm sóc và yêu thương, cả hai người đều cảm thấy được bảo vệ và an toàn bên nhau. Tình yêu đang tự nhiên lớn lên và bừng nở, như một khu vườn được tưới mát bởi sự tận tâm. Nếu xuất hiện ngược, hãy chú ý đến sự mất cân bằng trong việc cho và nhận — có thể một người đang cho quá nhiều mà quên đi bản thân. Bạn vừa là đóa hoa đang được tưới tắm, cũng là người cầm vòi tưới — đừng quên tự chăm sóc chính mình trước khi trao đi.'
  }},
  {id:4, emoji:'👑', name:{zh:'皇帝',en:'The Emperor',es:'El Emperador',fr:'L\'Empereur',th:'จักรพรรดิ',vi:'Hoàng Đế'}, meaning:{
    zh:'秩序与守护，稳稳托住的力量。这张牌在感情中出现，意味着你们的关系需要一份沉稳与可靠——它意味着责任、边界与可依赖的承诺。逆位时，提醒你检视关系中是否有控制欲过强或缺乏沟通的问题，健康的关系需要柔软与坚定并存。爱不是牢笼，而是城堡——它提供庇护的同时，也允许对方自由地呼吸。',
    en:'Order and protection — a steady, grounding force. In love, this card signals the need for stability and reliability — responsibility, boundaries, and dependable commitment. Reversed, it urges you to examine whether control or poor communication is eroding the bond; a healthy relationship blends firmness with softness. Love is not a cage but a castle — it shelters while still allowing the other to breathe freely.',
    es:'Orden y protección — una fuerza firme y estable. En el amor, esta carta señala la necesidad de estabilidad y fiabilidad — responsabilidad, límites y compromiso confiable. Invertido, le insta a examinar si el control o la mala comunicación está erosionando el vínculo; una relación sana mezcla firmeza con suavidad. El amor no es una jaula sino un castillo — resguarda mientras permite que el otro respire libremente.',
    fr:'Ordre et protection — une force stable et rassurante. En amour, cette carte signale le besoin de stabilité et de fiabilité — responsabilité, limites et engagement fiable. Inversé, elle vous invite à examiner si le contrôle ou la mauvaise communication érode le lien ; une relation saine allie fermeté et douceur. L\'amour n\'est pas une cage mais un château — il abrite tout en laissant l\'autre respirer librement.',
    th:'ความเป็นระเบียบและการปกป้อง — พลังที่มั่นคง ในความรัก ไพ่นี้บอกว่าความสัมพันธ์ต้องการความมั่นคงและเชื่อถือได้ — ความรับผิดชอบ ขอบเขต และข้อมั่นสัญญาที่น่าไว้วางใจ เมื่อกลับด้าน มันกระตุ้นให้คุณตรวจสอบว่าการควบคุมหรือการสื่อสารที่ไม่ดีกำลังทำลายสายสัมพันธ์หรือไม่ ความสัมพันธ์ที่ดีต้องผสมผสานความมั่นคงกับความอ่อนโยน ความรักไม่ใช่กรงเล็บแต่เป็นปราสาท — มันให้ที่หลบภัยในขณะที่ยังคงให้อีกฝ่ายหายใจอย่างเสรี',
    vi:'Trật tự và bảo vệ — một sức mạnh vững chãi. Trong tình yêu, lá bài này nhắc nhở về tầm quan trọng của sự ổn định và tin cậy, bạn đang cần hoặc đang xây dựng một nền tảng vững chắc cho mối quan hệ bằng trách nhiệm, ranh giới và cam kết đáng tin cậy. Nếu xuất hiện ngược, hãy chú ý đến sự cứng rắn thái quá hoặc thiếu sự linh hoạt — có thể ai đó đang kiểm soát quá nhiều hoặc không chịu lắng nghe. Tình yêu là lâu đài chứ không phải lồng chim — nó che chở nhưng vẫn cho người kia không gian để thở tự do.'
  }},
  {id:5, emoji:'⛪', name:{zh:'教皇',en:'The Hierophant',es:'El Sumo Sacerdote',fr:'Le Pape',th:'ประมุขสงฆ์',vi:'Giáo Hoàng'}, meaning:{
    zh:'指引与信念，灵魂层面的契合。这张牌暗示你们的感情建立在共同的价值观与精神追求之上——这是超越表面的深层连接，需要双方共同成长。逆位时，提醒你反思是否有盲从外界标准而忽视内心真实声音的情况，真正的契合来自灵魂而非形式。不必为了迎合世界的期待而阉割爱情最真实的模样——你们的信仰只在你们两人之间有效。',
    en:'Guidance and faith — souls aligned on a deeper level. This card suggests your bond rests on shared values and spiritual pursuits — a connection beyond the surface that calls for mutual growth. Reversed, it asks you to question whether you\'re blindly following external standards instead of honoring your own truth; real alignment comes from the soul, not from convention. You don\'t need to shrink your love to fit the world\'s expectations — your faith only needs to make sense between the two of you.',
    es:'Guía y fe — las almas se alinean en un nivel más profundo. Esta carta sugiere que su vínculo descansa en valores compartidos y búsquedas espirituales — una conexión más allá de la superficie que exige crecimiento mutuo. Invertido, le pide que cuestione si está siguiendo ciegamente estándares externos en lugar de honrar su verdad; la alineación real viene del alma, no de la convención. No necesita encoger su amor para encajar en las expectativas del mundo — su fe solo necesita tener sentido entre los dos.',
    fr:'Guidance et foi — les âmes s\'alignent au plus profond. Cette carte suggère que votre lien repose sur des valeurs partagées et des quêtes spirituelles — une connexion au-delà de la surface qui appelle une croissance mutuelle. Inversé, il vous demande si vous suivez aveuglément des normes extérieures au lieu d\'honorer votre vérité ; l\'alignement réel vient de l\'âme, pas de la convention. Vous n\'avez pas besoin de réduire votre amour pour qu\'il s\'adapte aux attentes du monde — votre foi n\'a de sens qu\'entre vous deux.',
    th:'การชี้นำและความศรัทธา — วิญญาณเชื่อมโยงกันในระดับลึก ไพ่นี้บอกว่าความผูกพันของคุณตั้งอยู่บนค่านิยมและการแสวงหาทางจิตวิญญาณร่วมกัน — การเชื่อมโยงที่ลึกกว่าผิวเนื้อและเรียกร้องให้เติบโตด้วยกัน เมื่อกลับด้าน มันถามว่าคุณกำลังปิดตาเชื่อมตามมาตรฐานภายนอกแทนที่จะเคารพความจริงของตัวเองหรือไม่ ความสอดคล้องจริงมาจากวิญญาณไม่ใช่จากธรรมเนียม คุณไม่จำเป็นต้องย่อขนาดความรักเพื่อให้เข้ากับความคาดหวังของโลก — ความศรัทธาของคุณต้องมีความหมายระหว่างสองคนเท่านั้น',
    vi:'Dẫn dắt và niềm tin — tâm hồn kết nối ở tầng sâu hơn. Đây là lá bài về sự kết nối tâm linh và giá trị chung, mối quan hệ xây dựng trên nền tảng niềm tin và mục đích chung — một sợi dây liên kết vượt xa bề mặt, đòi hỏi cả hai cùng trưởng thành. Nếu xuất hiện ngược, hãy xem xét lại những kỳ vọng đang ảnh hưởng đến tình yêu — bạn có đang mù quáng theo chuẩn mực bên ngoài mà bỏ quên tiếng nói thật của trái tim? Sự đồng điệu thật đến từ linh hồn chứ không phải hình thức. Đừng thu nhỏ tình yêu để vừa vặn với kỳ vọng của thế giới — đức tin của hai người chỉ cần có ý nghĩa giữa chính các bạn.'
  }},
  {id:6, emoji:'💕', name:{zh:'恋人',en:'The Lovers',es:'Los Enamorados',fr:'Les Amoureux',th:'คู่รัก',vi:'Tình Nhân'}, meaning:{
    zh:'抉择与诱惑，关系来到十字路口。这张牌直指感情中最关键的选择时刻——它意味着你正面临一个将深刻影响关系走向的决策，需要忠于内心。逆位时，提醒你莫因一时诱惑偏离本心，真爱往往需要穿越迷雾才能看清，对话与诚实是此刻最重要的功课。真正的爱不是没有岔路，而是在每个岔路口都选择了同一个方向。',
    en:'A crossroads of choice — your relationship faces a pivotal decision. This card points to the most critical moment in love — you are facing a choice that will deeply shape where the relationship goes, and it demands loyalty to your heart. Reversed, it warns against letting fleeting temptation pull you off course; true love often requires navigating through fog before becoming clear. Real love isn\'t about having no detours — it\'s about choosing the same direction at every crossroad.',
    es:'Una encrucijada de elección — su relación enfrenta una decisión crucial. Esta carta señala el momento más crítico del amor — usted enfrenta una elección que moldeará profundamente el rumbo de la relación, y exige lealtad al corazón. Invertido, advierte contra dejarse desviar por tentaciones pasajeras; el amor verdadero a menudo requiere atravesar la niebla antes de volverse claro. El amor real no se trata de no tener desvíos — se trata de elegir la misma dirección en cada encrucijada.',
    fr:'Un carrefour de choix — votre relation fait face à une décision cruciale. Cette carte désigne le moment le plus critique de l\'amour — vous faites face à un choix qui façonnera profondément l\'avenir de la relation, et il exige loyauté envers votre cœur. Inversé, il avertit contre les tentations passagères ; l\'amour véritable demande souvent de traverser le brouillard avant de devenir clair. Le véritable amour ne consiste pas à éviter les détours — c\'est choisir la même direction à chaque carrefour.',
    th:'ทางแยกแห่งการเลือก — ความสัมพันธ์ของคุณเผชิญการตัดสินใจสำคัญ ไพ่นี้ชี้ไปยังช่วงเวลาสำคัญที่สุดในความรัก — คุณกำลังเผชิญกับทางเลือกที่จะขึ้นรูปทิศทางของความสัมพันธ์อย่างลึกซึ้ง และต้องการความภักดีต่อหัวใจ เมื่อกลับด้าน มันเตือนว่าอย่าปล่อยให้การล่อลวงชั่วคราวหลอกล่อคุณ ความรักแท้มักต้องผ่านหมอกก่อนจะเห็นชัด ความรักที่แท้จริงไม่ใช่การไม่มีทางแยก — แต่คือการเลือกทิศทางเดียวกันทุกครั้งที่ถึงทางแยก',
    vi:'Ngã tư của sự lựa chọn — mối quan hệ đối mặt với quyết định quan trọng. Đây là khoảnh khắc để nhìn sâu vào bản chất của mối quan hệ và chọn con đường phù hợp nhất với lòng mình. Việc này đòi hỏi sự trung thực tuyệt đối với bản thân lẫn đối phương, bởi quyết định bạn đưa ra sẽ định hình toàn bộ tương lai của tình yêu. Nếu xuất hiện ngược, hãy cẩn thận với những quyết định vội vàng hoặc để ngoại cảnh chi phối trái tim. Tình yêu đích thực không phải là không có ngã rẽ — mà là ở mỗi ngã rẽ, hai người vẫn chọn cùng một hướng.'
  }},
  {id:7, emoji:'🏛️', name:{zh:'战车',en:'The Chariot',es:'El Carro',fr:'Le Chariot',th:'รถศึก',vi:'Cỗ Xe Chiến Thắng'}, meaning:{
    zh:'意志与征服，携手跨越障碍。这张牌象征着坚定的决心与胜利——你们的感情正经历一个需要共同努力跨越挑战的阶段，唯有同舟共济方能抵达彼岸。逆位时，暗示可能存在方向不一致或动力分散的问题，沟通彼此的目标与愿景是破解之道。爱是一场并肩的远征，只有当两匹马朝着同一个方向奔跑，战车才能真正疾驰。',
    en:'Willpower and triumph — overcoming obstacles together. This card symbolizes unwavering determination — your relationship is navigating a phase that demands mutual effort to overcome challenges; only rowing together will get you to the other shore. Reversed, it hints at diverging directions or scattered momentum; aligning your goals and visions through honest dialogue is the remedy. Love is a side-by-side expedition — the chariot only races forward when both horses run in the same direction.',
    es:'Fuerza de voluntad y triunfo — superando obstáculos juntos. Esta carta simboliza una determinación inquebrantable — su relación atraviesa una fase que exige esfuerzo mutuo para superar desafíos; solo remando juntos llegarán a la otra orilla. Invertido, sugiere direcciones divergentes o impulso disperso; alinear sus metas y visiones mediante un diálogo honesto es el remedio. El amor es una expedición hombro con hombro — el carro solo avanza cuando ambos caballos corren en la misma dirección.',
    fr:'Volonté et triomphe — surmonter les obstacles ensemble. Cette carte symbolise une détermination inébranlable — votre relation traverse une phase qui exige un effort mutuel pour surmonter les défis ; seule la navigation conjointe vous mènera à l\'autre rive. Inversé, il suggère des directions divergentes ou un élan dispersé ; aligner vos objectifs et visions par un dialogue honnête est le remède. L\'amour est une expédition côte à côte — le char n\'avance que quand les deux chevaux courent dans la même direction.',
    th:'พลังจิตและชัยชนะ — เอาชนะอุปสรรคไปด้วยกัน ไพ่นี้สื่อถึงความตั้งใจอันไม่สั่นคลอน — ความสัมพันธ์ของคุณกำลังเผชิญกับช่วงที่ต้องใช้ความพยายามร่วมกันเพื่อเอาชนะอุปสรรค การพายเรือด้วยกันเท่านั้นจะพาคุณถึงฝั่งโลกอีกด้าน เมื่อกลับด้าน มันบอกถึงทิศทางที่แตกต่างหรือแรงขับที่กระจาย การปรับทิศทางเป้าหมายและวิสัยทัศน์ผ่านการสื่อสารตรงๆ คือทางแก้ ความรักเป็นการเดินทางเคียงข้างกัน — รถศึกจะวิ่งไปข้างหน้าได้ก็ต่อเมื่อทั้งสองม้าวิ่งในทิศทางเดียวกัน',
    vi:'Ý chí và thắng lợi — vượt qua chướng ngại cùng nhau. Trong tình yêu, đây là lá bài của sự quyết tâm và ý chí vượt khó, mối quan hệ đang đi qua giai đoạn đòi hỏi nỗ lực song song để vượt qua thử thách — chỉ có cùng chèo một thuyền mới đến được bờ bên kia. Nếu xuất hiện ngược, hãy kiểm tra xem hai người có đang cùng hướng không, hoặc động lực có đang phân tán — việc thống nhất mục tiêu qua đối thoại chân thành chính là chìa khóa. Tình yêu là chuyến đi kề vai — cỗ xe chỉ lao tới khi cả hai con ngựa đều phi cùng một hướng.'
  }},
  {id:8, emoji:'💪', name:{zh:'力量',en:'The Strength',es:'La Fuerza',fr:'La Force',th:'พละกำลัง',vi:'Sức Mạnh'}, meaning:{
    zh:'内在勇气，柔韧却不可战胜。这张牌在感情中的出现，是对你内心力量的肯定——真正的强大不是坚硬如铁，而是以温柔与耐心化解冲突、以韧性守护关系。逆位时，提醒你可能忽略了内在的声音或压抑了真实感受，柔弱胜刚强，学会示弱是一种更高的勇气。最深沉的爱，不是战胜对方，而是驯服自己心中的猛兽。',
    en:'Inner courage — gentle yet invincible. When this card appears in love, it affirms your inner strength — true power isn\'t hardness, but dissolving conflicts with gentleness and patience, protecting the bond with resilience. Reversed, it suggests you may be ignoring your inner voice or suppressing real feelings; softness conquers hardness, and learning to be vulnerable is a higher form of courage. The deepest love is not about conquering the other — it is about taming the wild beast within yourself.',
    es:'Coraje interior — suave pero invencible. Cuando esta carta aparece en el amor, afirma tu fuerza interior — el verdadero poder no es la dureza, sino disolver conflictos con gentileza y paciencia, protegiendo el vínculo con resiliencia. Invertido, sugiere que puedes estar ignorando tu voz interior o suprimiendo sentimientos reales; la suavidad conquista la dureza, y aprender a ser vulnerable es una forma superior de coraje. El amor más profundo no se trata de conquistar al otro — se trata de domar la bestia salvaje dentro de ti.',
    fr:'Courage intérieur — doux mais invincible. Quand cette carte apparaît en amour, elle affirme votre force intérieure — le vrai pouvoir n\'est pas la dureté, mais dissoudre les conflits avec douceur et patience, protégeant le lien avec résilience. Inversé, il suggère que vous ignorez peut-être votre voix intérieure ou refoulez vos sentiments ; la douceur conquiert la dureté, et apprendre la vulnérabilité est une forme supérieure de courage. L\'amour le plus profond ne consiste pas à conquérir l\'autre — il s\'agit d\'apprivoiser la bête sauvage en vous-même.',
    th:'ความกล้าภายใน — อ่อนโยนแต่ไร้พ่าย เมื่อไพ่นี้ปรากฏในความรัก มันยืนยันพลังภายในของคุณ — พลังที่แท้จริงไม่ใช่ความแข็งกระด้าง แต่คือการละลายความขัดแย้งด้วยความอ่อนโยนและความอดทน ปกป้องความผูกพันด้วยความยืดหยุ่น เมื่อกลับด้าน มันเตือนว่าคุณอาจเพิกเฉยต่อเสียงภายในหรือกดทับความรู้สึกจริง ความอ่อนโยนเอาชนะความแข็งกระด้าง การเรียนรู้ที่จะเปิดเผยความเปราะบางเป็นความกล้าในระดับสูงกว่า ความรักที่ลึกซึ้งที่สุดไม่ใช่การเอาชนะอีกฝ่าย — แต่คือการปราบสัตว์ร้ายในใจตัวเอง',
    vi:'Can đảm bên trong — dịu dàng nhưng bất khả chiến bại. Trong tình yêu, lá bài này khẳng định sức mạnh nội tâm của bạn — quyền lực đích thực không phải sự cứng rắn, mà là hóa giải xung đột bằng sự dịu dàng và kiên nhẫn, bảo vệ mối quan hệ bằng sự kiên cường. Nếu xuất hiện ngược, có thể bạn đang bỏ qua tiếng nói bên trong hoặc kìm nén cảm xúc thật — mềm mỏng thắng cứng rắn, học cách yếu đuối là một dạng can đảm cao cả hơn. Tình yêu sâu đậm nhất không phải là chiến thắng đối phương — mà là thuần phục con thú hoang trong chính mình.'
  }},
  {id:9, emoji:'🕯️', name:{zh:'隐士',en:'The Hermit',es:'El Ermitaño',fr:'L\'Ermite',th:'นักบวชเรี่ยมใจ',vi:'Ẩn Sĩ'}, meaning:{
    zh:'独处与内观，答案在内心深处。这张牌在感情中出现，不是分离的征兆，而是提醒你们需要个人空间去思考、成长与自我整合——真正的亲密需要先与自我和解。逆位时，暗示可能过度封闭或逃避关系中的问题，有时独自行走是为了更好地相遇。独处不是孤独，而是灵魂与自己谈判的密室——走出那扇门时，你将带着更清晰的自己回到爱中。',
    en:'Solitude and introspection — the answer lies within. In love, this card isn\'t a sign of separation, but a reminder that you need personal space to think, grow, and integrate — true intimacy requires making peace with yourself first. Reversed, it suggests you may be isolating too much or avoiding relationship issues; sometimes walking alone is the path to a better reunion. Solitude is not loneliness — it is the private chamber where the soul negotiates with itself. When you step out, you return to love with a clearer self.',
    es:'Soledad e introspección — la respuesta está dentro. En el amor, esta carta no es señal de separación, sino un recordatorio de que necesitas espacio personal para pensar, crecer e integrarte — la verdadera intimidad requiere hacer las paces contigo mismo primero. Invertido, sugiere que puedes estar aislándote demasiado o evitando los problemas de la relación; a veces caminar solo es el camino hacia una mejor reunión. La soledad no es loneliness — es la cámara privada donde el alma negocia consigo misma. Cuando salgas, volverás al amor con un yo más claro.',
    fr:'Solitude et introspection — la réponse est en vous. En amour, cette carte n\'est pas un signe de séparation, mais un rappel que vous avez besoin d\'espace personnel pour penser, grandir et vous intégrer ; l\'intimité véritable exige d\'abord de faire la paix avec soi-même. Inversé, il suggère que vous vous isolez trop ou fuyez les problèmes de la relation ; parfois marcher seul est le chemin vers de meilleures retrouvailles. La solitude n\'est pas l\'isolement — c\'est la chambre privée où l\'âme négocie avec elle-même. Quand vous en sortirez, vous reviendrez à l\'amour avec un soi plus clair.',
    th:'ความเงียบและการสำรวจภายใน — คำตอบอยู่ในใจ ในความรัก ไพ่นี้ไม่ใช่สัญญาณของการแยกทาง แต่เป็นการเตือนว่าคุณต้องการพื้นที่ส่วนตัวเพื่อคิด เติบโต และรวบรวมตัวเอง — ความใกล้ชิดแท้จริงต้องการการคืนดีกับตัวเองก่อน เมื่อกลับด้าน มันบอกว่าคุณอาจปิดตัวมากเกินไปหรือหนีปัญหาในความสัมพันธ์ บางครั้งการเดินคนเดียวคือทางสู่การพบกันที่ดีกว่า ความเงียบไม่ใช่ความโดดเดี่ยว — แต่คือห้องลับที่วิญญาณเจรจากับตัวเอง เมื่อคุณเดินออกไป คุณจะกลับมาหาความรักด้วยตัวตนที่ชัดเจนขึ้น',
    vi:'Cô đơn và nội quan — câu trả lời nằm ở sâu bên trong. Trong tình yêu, lá bài này không phải điềm báo chia ly, mà là lời nhắc bạn cần không gian riêng để suy nghĩ, trưởng thành và chữa lành — sự gần gũi đích thực cần trước hết hòa giải với chính mình. Nếu xuất hiện ngược, có thể bạn đang tự cô lập quá mức hoặc né tránh vấn đề trong mối quan hệ — đôi khi đi một mình là để gặp lại nhau tốt đẹp hơn. Cô đơn không phải lạc lõng — mà là căn phòng kín nơi tâm hồn tự đàm phán với chính nó, và khi bước ra, bạn sẽ mang một phiên bản rõ ràng hơn của mình trở lại tình yêu.'
  }},
  {id:10, emoji:'☸️', name:{zh:'命运之轮',en:'Wheel of Fortune',es:'Rueda de la Fortuna',fr:'Roue de Fortune',th:'วงล้อแห่งโชคชะตา',vi:'Bánh Xe Số Phận'}, meaning:{
    zh:'转变与循环，命运正在转动。这张牌带来宇宙级的信息：你们的关系正处于一个关键的转折点上，过去的积累正在转化为新的可能，幸运的天平正在向你们倾斜。逆位时，提醒你不要抗拒改变，命运之轮从不后退，接纳它才能顺势而为，乘风破浪。命运不偏爱任何人，但它眷顾那些愿意在旋转中保持信念的灵魂。',
    en:'Transformation and cycles — destiny is turning in your favor. This card carries a cosmic message: your relationship is at a pivotal turning point, past efforts are transforming into new possibilities, and fortune\'s scales are tipping your way. Reversed, it reminds you not to resist change; the wheel of fortune never moves backward, and only by embracing it can you ride the current. Destiny favors no one — but it smiles on souls who keep faith while the wheel spins.',
    es:'Transformación y ciclos — el destino gira a su favor. Esta carta trae un mensaje cósmico: su relación está en un punto de inflexión, los esfuerzos pasados se transforman en nuevas posibilidades, y la balanza de la fortuna se inclina hacia ustedes. Invertido, le recuerda no resistir al cambio; la rueda de la fortuna nunca retrocede, y solo abrazándola podrá navegar la corriente. El destino no favorece a nadie — pero sonríe a las almas que mantienen la fe mientras la rueda gira.',
    fr:'Transformation et cycles — le destin tourne en votre faveur. Cette carte porte un message cosmique : votre relation est à un tournant décisif, les efforts passés se transforment en nouvelles possibilités, et la balance de la fortune penche en votre faveur. Inversé, il vous rappelle de ne pas résister au changement ; la roue de la fortune ne recule jamais, et ce n\'est qu\'en l\'embrassant que vous pourrez surfer sur le courant. Le destin ne favorise personne — mais il sourit aux âmes qui gardent la foi pendant que la roue tourne.',
    th:'การเปลี่ยนแปลงและวัฏจักร — โชคชะตากำลังหมุนเข้ามา ไพ่นี้นำข้อความจากจักรวาล: ความสัมพันธ์ของคุณอยู่ที่จุดเปลี่ยนสำคัญ ความพยายามในอดีตกำลังเปลี่ยนเป็นโอกาสใหม่ และตาชั่งแห่งโชคชะตาเอนเข้าหาคุณ เมื่อกลับด้าน มันเตือนว่าอย่าต่อต้านการเปลี่ยนแปลง วงล้อแห่งโชคชะตาไม่เคยถอยหลัง การยอมรับมันเท่านั้นจะพาคุณไปกับกระแส โชคชะตาไม่เลือกข้างใคร — แต่มันยิ้มให้วิญญาณที่ยังเชื่อในขณะที่วงล้อหมุน',
    vi:'Biến đổi và chu kỳ — vận mệnh đang xoay chuyển đến với bạn. Lá bài này mang thông điệp vũ trụ: mối quan hệ đang ở bước ngoặt quan trọng, những nỗ lực quá khứ đang biến thành khả năng mới, cán cân may mắn đang nghiêng về phía bạn. Nếu xuất hiện ngược, đừng chống lại sự thay đổi — bánh xe số phận không bao giờ quay ngược, chỉ khi chấp nhận nó bạn mới có thể thuận gió mà đi. Vận mệnh không thiên vị ai — nhưng nó mỉm cười với những linh hồn giữ vững niềm tin khi bánh xe xoay chuyển.'
  }},
  {id:11, emoji:'⚖️', name:{zh:'正义',en:'Justice',es:'La Justicia',fr:'La Justice',th:'ความยุติธรรม',vi:'Công Lý'}, meaning:{
    zh:'因果与平衡，宇宙在精准回应。这张牌出现于感情中，是对你们关系公正性的审视——每一个选择都有回响，你的付出与收获终将趋于平衡。逆位时，提示你需要诚实地审视关系中是否存在失衡之处，唯有基于真相的和解才能带来持久的安宁。正义不是冰冷的裁决，而是宇宙在问你：你是否愿意对真相负责？',
    en:'Cause and balance — the universe responds with precision. In love, this card calls for an honest audit of your relationship — every choice has an echo, and what you give and receive will eventually find equilibrium. Reversed, it urges you to examine whether imbalance lives within the bond; only reconciliation grounded in truth can bring lasting peace. Justice is not cold verdict — it is the universe asking: are you willing to be accountable to the truth?',
    es:'Causa y equilibrio — el universo responde con precisión. En el amor, esta carta pide una auditoría honesta de su relación — cada elección tiene un eco, y lo que dan y reciben eventualmente encontrará equilibrio. Invertido, le insta a examinar si hay desequilibrio en el vínculo; solo la reconciliación basada en la verdad puede traer paz duradera. La justicia no es un veredicto frío — es el universo preguntando: ¿estás dispuesto a ser responsable ante la verdad?',
    fr:'Cause et équilibre — l\'univers répond avec précision. En amour, cette carte demande un audit honnête de votre relation — chaque choix a un écho, et ce que vous donnez et recevez finira par trouver son équilibre. Inversé, il vous invite à examiner si un déséquilibre habite le lien ; seule la réconciliation fondée sur la vérité peut apporter une paix durable. La justice n\'est pas un verdict froid — c\'est l\'univers qui demande : êtes-vous prêt à répondre de la vérité ?',
    th:'เหตุและสมดุล — จักรวาลตอบสนองอย่างแม่นยำ ในความรัก ไพ่นี้เรียกร้องการตรวจสอบความสัมพันธ์ของคุณอย่างซื่อสัตย์ — ทุกการเลือกมีเสียงสะท้อน สิ่งที่คุณให้และรับจะพบจุดสมดุลในที่สุด เมื่อกลับด้าน มันกระตุ้นให้ตรวจสอบว่ามีความไม่สมดุลในความสัมพันธ์หรือไม่ ความปรองดองที่ตั้งอยู่บนความจริงเท่านั้นจะนำสันติมาได้ ความยุติธรรมไม่ใช่คำตัดสินที่เย็นชา — แต่เป็นจักรวาลที่ถามว่า: คุณยินดีรับผิดชอบต่อความจริงหรือไม่',
    vi:'Nhân quả và cân bằng — vũ trụ đáp trả chính xác. Trong tình yêu, lá bài này kêu gọi một cuộc kiểm toán trung thực về mối quan hệ — mọi lựa chọn đều có hồi âm, những gì bạn cho và nhận sẽ tìm được cân bằng. Nếu xuất hiện ngược, hãy xem xét xem có sự mất cân bằng nào trong tình yêu — chỉ có hòa giải dựa trên sự thật mới mang lại bình yên bền vững. Công lý không phải bản án lạnh lùng — mà là vũ trụ đang hỏi: bạn có sẵn sàng chịu trách nhiệm trước sự thật?'
  }},
  {id:12, emoji:'🙃', name:{zh:'倒吊人',en:'The Hanged Man',es:'El Colgado',fr:'Le Pendu',th:'คนแขวนหัว',vi:'Kẻ Treo Ngược'}, meaning:{
    zh:'放下与臣服，另一种视角的智慧。这张牌的出现，是你与关系都需要换一种眼光审视的时刻——有时候暂停与臣服，比强行推进更能带来突破。逆位时，提醒你可能过于执着于某个结果，学会放下执念，反而能让答案自动浮现。悬挂不是惩罚，而是宇宙在为你重装视角——当你重新站起，世界已不再是旧时的模样。',
    en:'Surrender and release — wisdom from a different perspective. This card signals a moment when you and your relationship need new eyes — sometimes pausing and surrendering brings more breakthrough than pushing forward. Reversed, it warns you may be clinging too tightly to a desired outcome; letting go of fixation allows the answer to surface on its own. Suspension is not punishment — it is the universe recalibrating your vision. When you rise again, the world will not look the same.',
    es:'Rendición y liberación — sabiduría desde otra perspectiva. Esta carta señala un momento en que usted y su relación necesitan nuevos ojos — a veces pausar y rendirse trae más avance que empujar hacia adelante. Invertido, advierte que puede estar aferrándose demasiado a un resultado deseado; soltar la fijación permite que la respuesta surja por sí sola. La suspensión no es castigo — es el universo recalibrando su visión. Cuando se levante de nuevo, el mundo no se verá igual.',
    fr:'Lâcher-prise et abandon — sagesse d\'une autre perspective. Cette carte signale un moment où vous et votre relation avez besoin d\'un regard neuf — parfois s\'arrêter et s\'abandonner apporte plus de percée que d\'avancer de force. Inversé, il avertit que vous vous accrochez trop à un résultat escompté ; lâcher l\'obsession permet à la réponse d\'émerger d\'elle-même. La suspension n\'est pas un châtiment — c\'est l\'univers qui recalibre votre vision. Quand vous vous relèverez, le monde n\'aura plus la même apparence.',
    th:'การยอมแพ้และการปล่อยวาง — ภูมิปัญญาจากมุมมองใหม่ ไพ่นี้บอกว่าคุณและความสัมพันธ์ต้องการสายตาใหม่ — บางครั้งการหยุดและยอมรับนำมาซึ่งความก้าวหน้ามากกว่าการดันต่อไป เมื่อกลับด้าน มันเตือนว่าคุณอาจยึดติดกับผลลัพธ์มากเกินไป การปล่อยวางจะให้คำตอบปรากฏเอง การแขวนไม่ใช่การลงโทษ — แต่เป็นจักรวาลที่ปรับทัศนวิสัยให้คุณ เมื่อคุณลุกขึ้นอีกครั้ง โลกจะไม่เหมือนเดิม',
    vi:'Buông bỏ và đầu hàng — sự khôn ngoan từ góc nhìn khác. Lá bài này báo hiệu khoảnh khắc bạn và mối quan hệ cần đôi mắt mới — đôi khi dừng lại và chấp nhận mang lại đột phá hơn là cố tiến lên. Nếu xuất hiện ngược, có thể bạn đang bám víu quá chặt vào một kết quả mong muốn — buông bỏ chấp niệm sẽ để câu trả lời tự lộ diện. Treo ngược không phải hình phạt — mà là vũ trụ đang cài đặt lại lăng kính cho bạn, và khi đứng dậy, thế giới sẽ không còn như cũ.'
  }},
  {id:13, emoji:'💀', name:{zh:'死神',en:'Death',es:'La Muerte',fr:'La Mort',th:'เจ้าแห่งความตาย',vi:'Cái Chết'}, meaning:{
    zh:'结束与蜕变，旧篇章的翻页。这张牌在感情中从不意味着真正的终结——它象征的是一种深刻的转化，一个阶段向另一个阶段的蜕变，旧有的模式正在被彻底更新。逆位时，提示你抗拒变化可能正在造成不必要的痛苦，拥抱结束才能迎来真正的新生。凤凰必须先燃尽，才能从灰烬中展翅——你害怕的终点，也许正是重生的起点。',
    en:'Endings and transformation — a new chapter begins. In love, this card never means a true ending — it symbolizes profound transformation, the metamorphosis from one phase to another, old patterns being completely renewed. Reversed, it suggests that resisting change may be causing unnecessary pain; embracing the end is the only way to welcome genuine rebirth. The phoenix must burn before it can rise from the ashes — the endpoint you fear may be the very beginning of renewal.',
    es:'Finales y transformación — un nuevo capítulo comienza. En el amor, esta carta nunca significa un verdadero final — simboliza una profunda transformación, la metamorfosis de una fase a otra, viejos patrones renovándose por completo. Invertido, sugiere que resistir al cambio puede estar causando dolor innecesario; abrazar el final es la única forma de dar la bienvenida a un renacimiento genuino. El fénix debe arder antes de poder alzarse de las cenizas — el final que temes puede ser el comienzo mismo de la renovación.',
    fr:'Fins et transformation — un nouveau chapitre commence. En amour, cette carte ne signifie jamais une véritable fin — elle symbolise une transformation profonde, la métamorphose d\'une phase à l\'autre, les anciens schémas se renouvelant complètement. Inversé, il suggère que résister au changement peut causer une souffrance inutile ; embrasser la fin est la seule voie vers une renaissance authentique. Le phénix doit brûler avant de pouvoir s\'élever des cendres — la fin que vous redoutez est peut-être le début même du renouveau.',
    th:'จุดจบและการเปลี่ยนแปลง — บทใหม่เริ่มต้น ในความรัก ไพ่นี้ไม่เคยหมายถึงการจบสิ้นที่แท้จริง — มันสื่อถึงการเปลี่ยนแปลงอย่างลึกซึ้ง การเปลี่ยนรูปจากช่วงหนึ่งไปสู่อีกช่วง รูปแบบเก่ากำลังถูกรื้อใหม่ทั้งหมด เมื่อกลับด้าน มันบอกว่าการต่อต้านการเปลี่ยนแปลงอาจก่อให้เกิดความเจ็บปวดโดยไม่จำเป็น การยอมรับการจบสิ้นคือทางเดียวที่จะต้อนรับการเกิดใหม่ ฟีนิกซ์ต้องไหม้ก่อนจะลุกขึ้นจากเถ้าถ่าน — จุดจบที่คุณกลัวอาจเป็นจุดเริ่มต้นของการเกิดใหม่',
    vi:'Kết thúc và hoán chuyển — một chương mới bắt đầu. Trong tình yêu, lá bài này không bao giờ là dấu hiệu của sự kết thúc thật — nó tượng trưng cho sự chuyển hóa sâu sắc, một giai đoạn lột xác sang giai đoạn khác, những khuôn mẫu cũ đang được làm mới hoàn toàn. Nếu xuất hiện ngược, việc chống lại thay đổi có thể đang gây đau khổ không cần thiết — ôm lấy kết thúc mới đón được sự tái sinh đích thực. Phượng hoàng phải cháy rụi trước khi vươn cánh từ đống tro tàn — điểm kết mà bạn sợ hãi, có thể chính là khởi đầu của sự hồi sinh.'
  }},
  {id:14, emoji:'🦋', name:{zh:'节制',en:'Temperance',es:'La Templanza',fr:'Tempérance',th:'ความสมดุล',vi:'Chừng Mực'}, meaning:{
    zh:'平衡与调和，在两极间找到节奏。这张牌出现于感情中，暗示你们需要找到属于两人的节奏——在给予与接受、理性与感性、独立与亲密之间找到动态的平衡。逆位时，提示关系中某一方可能付出或索取过度，中庸之道才是持久之策。爱不是走钢丝，而是在摇摆中找到属于你们的支点——两个半圆合一，才是完整的圆。',
    en:'Balance and harmony — finding rhythm between opposites. In love, this card suggests you need to find your shared rhythm — a dynamic equilibrium between giving and receiving, reason and emotion, independence and closeness. Reversed, it signals that one partner may be giving or taking too much; the middle way is the lasting one. Love isn\'t walking a tightrope — it\'s finding your shared fulcrum within the sway. Two half-circles becoming one whole — that is the complete circle.',
    es:'Equilibrio y armonía — encontrando ritmo entre opuestos. En el amor, esta carta sugiere que necesitan encontrar su ritmo compartido — un equilibrio dinámico entre dar y recibir, razón y emoción, independencia y cercanía. Invertido, señala que uno puede estar dando o tomando demasiado; el camino medio es el duradero. El amor no es caminar por la cuerda floja — es encontrar su fulcro compartido en el vaivén. Dos semicírculos haciéndose uno — ese es el círculo completo.',
    fr:'Équilibre et harmonie — trouver le rythme entre les contraires. En amour, cette carte suggère que vous devez trouver votre rythme commun — un équilibre dynamique entre donner et recevoir, raison et émotion, indépendance et proximité. Inversé, il signale qu\'un partenaire peut donner ou prendre trop ; la voie du milieu est la plus durable. L\'amour n\'est pas marcher sur un fil — c\'est trouver votre point d\'équilibre partagé dans le balancement. Deux demi-cercles ne font un cercle complet qu\'ensemble.',
    th:'สมดุลและความสามัคคี — หาจังหวะระหว่างสองขั้ว ในความรัก ไพ่นี้บอกว่าคุณต้องหาจังหวะร่วมกัน — สมดุลแบบไดนามิกระหว่างการให้และรับ เหตุผลและอารมณ์ ความเป็นอิสระและความใกล้ชิด เมื่อกลับด้าน มันบอกว่าฝ่ายหนึ่งอาจให้หรือรับมากเกินไป ทางสายกลางคือหนทางที่ยั่งยืน ความรักไม่ใช่การเดินบนเชือก — แต่คือการหาจุดศูนย์กลางร่วมในการแกว่ง สองครึ่งวงรวมกันจึงจะเป็นวงกลมบริบูรณ์',
    vi:'Cân bằng và hài hòa — tìm thấy nhịp điệu giữa hai thái cực. Trong tình yêu, lá bài này gợi ý bạn cần tìm nhịp chung — sự cân bằng động giữa cho và nhận, lý trí và cảm xúc, độc lập và gần gũi. Nếu xuất hiện ngược, có thể một bên đang cho hoặc lấy quá nhiều — trung đạo mới là bền vững. Tình yêu không phải đi trên dây — mà là tìm điểm tựa chung trong sự dao động. Hai nửa vòng tròn hòa làm một, mới là vòng tròn trọn vẹn.'
  }},
  {id:15, emoji:'🔗', name:{zh:'恶魔',en:'The Devil',es:'El Diablo',fr:'Le Diable',th:'ปีศาจ',vi:'Ác Quỷ'}, meaning:{
    zh:'束缚与执念，看见阴影才能超越。这张牌的出现是对关系中无形锁链的警示——它可能是恐惧、依赖、或是未解决的创伤在暗处牵制着你们。逆位时，意味着你们正在挣脱这些束缚，这过程虽然痛苦，但每一次对阴影的直视都是走向自由的关键一步。影子是光的证据——敢于凝视黑暗的人，才配拥有真正的光明。',
    en:'Bondage and attachment — face the shadow to transcend it. This card warns of invisible chains in your relationship — they may be fear, dependency, or unresolved trauma pulling strings in the dark. Reversed, it signals you are breaking free from these bonds; the process is painful, but every direct gaze at the shadow is a step toward freedom. Shadows are proof of light — only those who dare to stare into darkness deserve true illumination.',
    es:'Atadura y apego — enfrente la sombra para trascenderla. Esta carta advierte sobre cadenas invisibles en su relación — pueden ser miedo, dependencia o trauma no resuelto tirando de los hilos en la oscuridad. Invertido, señala que se está liberando de estas ataduras; el proceso es doloroso, pero cada mirada directa a la sombra es un paso hacia la libertad. Las sombras son prueba de luz — solo quienes se atreven a mirar la oscuridad merecen la verdadera iluminación.',
    fr:'Attachement et obsession — affrontez l\'ombre pour la transcender. Cette carte avertit de chaînes invisibles dans votre relation — elles peuvent être la peur, la dépendance ou des traumatismes non résolis tirant les ficelles dans l\'ombre. Inversé, il signale que vous vous libérez de ces liens ; le processus est douloureux, mais chaque regard direct sur l\'ombre est un pas vers la liberté. Les ombres sont la preuve de la lumière — seuls ceux qui osent regarder l\'obscurité méritent la véritable illumination.',
    th:'พันธนะและความยึดติด — เผชิญหน้ากับเงาเพื่อเลยล้ำ ไพ่นี้เตือนเกี่ยวกับโซ่ล่องหนในความสัมพันธ์ — อาจเป็นความกลัว การพึ่งพา หรือบาดแผลที่ยังไม่ได้รับการแก้ไขที่ดึงเส้นใยอยู่เบื้องหลัง เมื่อกลับด้าน มันบอกว่าคุณกำลังหลุดพ้นจากพันธนะเหล่านี้ กระบวนการนี้เจ็บปวด แต่ทุกครั้งที่เผชิญหน้ากับเงาคือก้าวสู่อิสรภาพ เงาคือหลักฐานของแสง — เฉพาะผู้ที่กล้าจ้องมองความมืดเท่านั้นที่สมควรได้รับแสงสว่างแท้จริง',
    vi:'Trói buộc và chấp niệm — đối mặt với bóng tối để vượt lên. Lá bài này cảnh báo về những sợi dây vô hình trong mối quan hệ — có thể là nỗi sợ, sự phụ thuộc, hay tổn thương chưa chữa lành đang giật dây trong bóng tối. Nếu xuất hiện ngược, bạn đang dần thoát khỏi những xiềng xích ấy — quá trình đau đớn, nhưng mỗi lần dám nhìn thẳng vào bóng tối là một bước tiến tới tự do. Bóng tối là chứng cứ của ánh sáng — chỉ những ai dám nhìn vào bóng tối mới xứng đáng có ánh sáng đích thực.'
  }},
  {id:16, emoji:'🗼', name:{zh:'塔',en:'The Tower',es:'La Torre',fr:'La Tour',th:'หอคอย',vi:'Tháp'}, meaning:{
    zh:'突变的觉醒，打碎幻象见真相。这是感情中最具震撼力的一张牌——它宣告旧有幻象的崩塌，随之而来的是痛苦但必要的真实觉醒。逆位时，暗示你可能还在抗拒这场必然的崩塌，而内在的觉醒早已势不可挡地发生，真正的解脱就在剧痛之后。雷击不是毁灭，而是宇宙在替你拆掉危楼——废墟之下，藏着比幻象更坚实的地基。',
    en:'Sudden awakening — illusions shatter to reveal truth. This is the most shocking card in love — it announces the collapse of old illusions, followed by a painful but necessary awakening to reality. Reversed, it suggests you may still be resisting this inevitable collapse, even as the inner awakening has already become unstoppable; true liberation lies just beyond the agony. Lightning is not destruction — it is the universe demolishing your dangerous structure for you. Beneath the rubble lies a foundation more solid than any illusion.',
    es:'Despertar repentino — las ilusiones se rompen para revelar la verdad. Esta es la carta más impactante del amor — anuncia el colapso de viejas ilusiones, seguido de un doloroso pero necesario despertar a la realidad. Invertido, sugiere que aún resiste este colapso inevitable, aunque el despertar interior ya se ha vuelto imparable; la verdadera liberación está justo después de la agonía. El rayo no es destrucción — es el universo demoliendo su estructura peligrosa. Bajo los escombros yace una base más sólida que cualquier ilusión.',
    fr:'Éveil soudain — les illusions se brisent pour révéler la vérité. C\'est la carte la plus bouleversante en amour — elle annonce l\'effondrement des vieilles illusions, suivi d\'un réveil douloureux mais nécessaire à la réalité. Inversé, il suggère que vous résistez encore à cet effondrement inévitable, alors que l\'éveil intérieur est déjà devenu irrésistible ; la véritable libération se trouve juste au-delà de l\'agonie. La foudre n\'est pas destruction — c\'est l\'univers qui démolit votre édifice dangereux. Sous les décombres gît un fondement plus solide que toute illusion.',
    th:'การตื่นรู้ทันใด — ภาพลวงแตกสลายเปิดเผยความจริง นี่คือไพ่ที่สะเทือนใจที่สุดในความรัก — มันประกาศการพังทลายของภาพลวงเก่า ตามด้วยการตื่นขึ้นสู่ความจริงที่เจ็บปวดแต่จำเป็น เมื่อกลับด้าน มันบอกว่าคุณอาจยังต่อต้านการพังทลายที่หลีกเลี่ยงไม่ได้นี้ แม้ว่าการตื่นรู้ภายในได้เกิดขึ้นไม่อาจหยุดยั้งแล้ว การปลดปล่อยแท้จริงรออยู่หลังความเจ็บปวด ฟ้าผ่าไม่ใช่การทำลาย — แต่เป็นจักรวาลที่รื้ออาคารเสี่ยงภัยให้คุณ ใต้ซากปรักหักพังมีรากฐานที่มั่นคงกว่าภาพลวงใดๆ',
    vi:'Tỉnh giác đột ngột — ảo ảnh vỡ tan để lộ ra sự thật. Đây là lá bài chấn động nhất trong tình yêu — nó tuyên bố sự sụp đổ của những ảo tưởng cũ, theo sau là sự thức tỉnh đau đớn nhưng cần thiết. Nếu xuất hiện ngược, có thể bạn vẫn đang chống lại sự sụp đổ tất yếu, trong khi sự thức tỉnh bên trong đã không thể ngăn cản — giải thoát thật sự nằm ngay sau cơn đau. Sấm sét không phải hủy diệt — mà là vũ trụ đang phá bỏ tòa nhà nguy hiểm giúp bạn, và dưới đống đổ nát là nền móng vững chắc hơn bất kỳ ảo tưởng nào.'
  }},
  {id:17, emoji:'⭐', name:{zh:'星星',en:'The Star',es:'La Estrella',fr:'L\'Étoile',th:'ดาว',vi:'Ngôi Sao'}, meaning:{
    zh:'希望与灵感，宇宙的疗愈之光。这是感情中最温柔的一张牌——它为经历过风暴的关系带来宁静与修复的力量，暗示你们正在进入一个充满希望与重建的阶段。逆位时，提示你可能暂时失去了与这份希望连接的能力，但请相信，星光从未消失，它只是在等待云层散去。每颗星都是一封来自宇宙的情书——即使你看不见它，它也从未停止发光。',
    en:'Hope and inspiration — cosmic healing light guides you. This is the gentlest card in love — it brings calm and restorative power to a relationship that has weathered storms, signaling a phase of hope and rebuilding. Reversed, it suggests you\'ve temporarily lost the ability to connect with that hope, but trust: starlight never vanishes — it simply waits for the clouds to part. Every star is a love letter from the cosmos — even when you cannot see it, it never stops shining.',
    es:'Esperanza e inspiración — la luz cósmica de sanación te guía. Esta es la carta más suave del amor — trae calma y poder restaurador a una relación que ha atravesado tormentas, señalando una fase de esperanza y reconstrucción. Invertido, sugiere que has perdido temporalmente la capacidad de conectar con esa esperanza, pero confía: la luz de las estrellas nunca desaparece — simplemente espera que las nubes se aparten. Cada estrella es una carta de amor del cosmos — incluso cuando no puedes verla, nunca deja de brillar.',
    fr:'Espoir et inspiration — la lumière de guérison cosmique vous guide. C\'est la carte la plus douce en amour — elle apporte calme et pouvoir restaurateur à une relation qui a traversé les tempêtes, signalant une phase d\'espoir et de reconstruction. Inversé, il suggère que vous avez temporairement perdu la capacité de vous connecter à cet espoir, mais ayez confiance : la lumière des étoiles ne disparaît jamais — elle attend simplement que les nuages se dissipent. Chaque étoile est une lettre d\'amour du cosmos — même quand vous ne la voyez pas, elle ne cesse jamais de briller.',
    th:'ความหวังและแรงบันดาลใจ — แสงรักษาจากจักรวาลนำทางคุณ นี่คือไพ่ที่อ่อนโยนที่สุดในความรัก — มันนำความสงบและพลังฟื้นฟูมาสู่ความสัมพันธ์ที่ผ่านพายุมาแล้ว ส่งสัญญาณช่วงเวลาแห่งความหวังและการสร้างใหม่ เมื่อกลับด้าน มันบอกว่าคุณอาจสูญเสียความสามารถในการเชื่อมต่อกับความหวังนั้นชั่วคราว แต่จงเชื่อ: แสงดาวไม่เคยหายไป — มันแค่รอให้เมฆจางหาย ทุกดวงดาวคือจดหมายรักจากจักรวาล — แม้คุณมองไม่เห็น มันก็ไม่เคยหยุดเปล่งแสง',
    vi:'Hy vọng và cảm hứng — ánh sáng chữa lành vũ trụ dẫn đường. Đây là lá bài dịu dàng nhất trong tình yêu — nó mang sự bình yên và sức mạnh chữa lành cho mối quan hệ đã vượt qua bão táp, báo hiệu giai đoạn tràn ngập hy vọng và xây dựng lại. Nếu xuất hiện ngược, bạn có thể tạm thời mất kết nối với niềm hy vọng ấy — nhưng hãy tin, ánh sao chưa từng biến mất, nó chỉ đang chờ mây tan đi. Mỗi vì sao là một bức thư tình từ vũ trụ — ngay cả khi bạn không nhìn thấy, nó vẫn không ngừng tỏa sáng.'
  }},
  {id:18, emoji:'🌙', name:{zh:'月亮',en:'The Moon',es:'La Luna',fr:'La Lune',th:'ดวงจันทร์',vi:'Mặt Trăng'}, meaning:{
    zh:'幻象与恐惧，直面内心深处的不安。这张牌在感情中出现，暗示你们的关系中可能存在未被说出口的恐惧或误解——月光之下，一切皆有可能是幻象。逆位时，意味着迷雾正在逐渐散去，你们正慢慢看清彼此与关系的真实模样，这过程虽然不安，却是走向真正连接的必经之路。月亮不说谎，它只是让你看到自己不敢在白天面对的真相。',
    en:'Illusion and fear — confront the unease within. In love, this card hints at unspoken fears or misunderstandings — under moonlight, everything could be an illusion. Reversed, it means the fog is slowly lifting, and you are beginning to see each other and the relationship as they truly are; unsettling, yet this is the only path to genuine connection. The moon does not lie — it merely reveals the truths you dare not face in daylight.',
    es:'Ilusión y miedo — enfrente la inquietud interior. En el amor, esta carta sugiere miedos no expresados o malentendidos — bajo la luz de la luna, todo podría ser una ilusión. Invertido, significa que la niebla se está disipando, y comienzan a verse mutuamente y a la relación como realmente son; inquietante, pero este es el único camino hacia una conexión genuina. La luna no miente — simplemente revela las verdades que no se atreven a enfrentar de día.',
    fr:'Illusion et peur — affrontez l\'inquiétude intérieure. En amour, cette carte suggère des peurs non dites ou des malentendus — au clair de lune, tout pourrait être une illusion. Inversé, il signifie que le brouillard se lève lentement, et vous commencez à vous voir l\'un l\'autre et la relation tels qu\'ils sont réellement ; dérangeant, mais c\'est le seul chemin vers une connexion authentique. La lune ne ment pas — elle révèle simplement les vérités que vous n\'osez pas affronter en plein jour.',
    th:'ภาพลวงและความกลัว — เผชิญหน้ากับความไม่สงบภายใน ในความรัก ไพ่นี้บอกถึงความกลัวที่ไม่กล้าพูดหรือความเข้าใจผิด — ใต้แสงจันทร์ ทุกอย่างอาจเป็นภาพลวง เมื่อกลับด้าน มันหมายถึงหมอกกำลังจางลง คุณเริ่มเห็นกันและกันและความสัมพันธ์ตามความเป็นจริง น่าไม่สบายใจ แต่นี่คือเส้นทางเดียวสู่การเชื่อมโยงแท้จริง ดวงจันทร์ไม่โกหก — มันเพียงเผยความจริงที่คุณไม่กล้าเผชิญในยามกลางวัน',
    vi:'Ảo ảnh và nỗi sợ — đối diện với bất an sâu thẳm. Trong tình yêu, lá bài này gợi ý những nỗi sợ chưa nói ra hoặc sự hiểu lầm — dưới ánh trăng, mọi thứ đều có thể là ảo ảnh. Nếu xuất hiện ngược, sương mù đang dần tan đi, bạn đang thấy rõ hơn bản chất thật của nhau và mối quan hệ — quá trình bất an nhưng là con đường duy nhất tới sự kết nối đích thực. Mặt trăng không nói dối — nó chỉ phơi bày những sự thật bạn không dám đối mặt trong ánh ban ngày.'
  }},
  {id:19, emoji:'☀️', name:{zh:'太阳',en:'The Sun',es:'El Sol',fr:'Le Soleil',th:'ดวงอาทิตย์',vi:'Mặt Trời'}, meaning:{
    zh:'喜悦与成功，生命力全面绽放。这是感情中最光明的一张牌——它宣告一段充满活力、喜悦与正向成长的关系阶段，一切都在向阳而生。逆位时，提示你可能暂时被乌云遮蔽了心中的阳光，但请记得，太阳从不真正消失，它只是在等待穿透云层的时机。阳光不属于任何一朵花，但每朵花都因它而盛开——你的快乐从不依赖别人，却能与对方共享光芒。',
    en:'Joy and success — vitality in full bloom. This is the brightest card in love — it announces a phase brimming with energy, joy, and positive growth; everything is turning toward the light. Reversed, it suggests clouds may have temporarily blocked your inner sunshine, but remember: the sun never truly disappears — it simply waits for the right moment to break through. Sunlight belongs to no single flower, yet every flower blooms because of it — your happiness never depends on another, yet you can share the radiance together.',
    es:'Alegría y éxito — vitalidad en plena floración. Esta es la carta más luminosa del amor — anuncia una fase rebosante de energía, alegría y crecimiento positivo; todo se vuelve hacia la luz. Invertido, sugiere que las nubes pueden haber bloqueado temporalmente su sol interior, pero recuerde: el sol nunca desaparece de verdad — simplemente espera el momento de atravesar las nubes. La luz del sol no pertenece a ninguna flor, pero cada flor florece gracias a ella — su felicidad nunca depende de otro, pero pueden compartir el resplandor juntos.',
    fr:'Joie et succès — vitalité en pleine floraison. C\'est la carte la plus lumineuse en amour — elle annonce une phase débordante d\'énergie, de joie et de croissance positive ; tout se tourne vers la lumière. Inversé, il suggère que les nuages ont peut-être temporairement bloqué votre soleil intérieur, mais rappelez-vous : le soleil ne disparaît jamais véritablement — il attend simplement le bon moment pour percer. La lumière du soleil n\'appartient à aucune fleur, pourtant chaque fleur éclot grâce à elle — votre bonheur ne dépend jamais d\'un autre, mais vous pouvez en partager l\'éclat ensemble.',
    th:'ความสุขและความสำเร็จ — พลังชีวิตเบ่งบานอย่างเต็มที่ นี่คือไพ่ที่สว่างที่สุดในความรัก — มันประกาศช่วงเวลาที่เต็มไปด้วยพลังงาน ความสุข และการเติบโตเชิงบวก ทุกอย่างหันเข้าหาแสง เมื่อกลับด้าน มันบอกว่าเมฆอาจบดบังแสงแดดในใจคุณชั่วคราว แต่จงจำไว้: ดวงอาทิตย์ไม่เคยหายไปจริงๆ — มันแค่รอเวลาที่จะทะลุผ่านเมฆ แสงแดดไม่ได้เป็นของดอกไม้ใดโดยเฉพาะ แต่ทุกดอกไม้บานเพราะมัน — ความสุขของคุณไม่เคยขึ้นกับใคร แต่คุณสามารถแบ่งปันแสงสว่างร่วมกัน',
    vi:'Vui sướng và thành công — sức sống nở rộ trọn vẹn. Đây là lá bài sáng chói nhất trong tình yêu — nó tuyên bố giai đoạn tràn ngập năng lượng, niềm vui và tăng trưởng tích cực, mọi thứ đều hướng về ánh sáng. Nếu xuất hiện ngược, mây đen có thể tạm che ánh dương trong lòng bạn — nhưng hãy nhớ, mặt trời không bao giờ thật sự biến mất, nó chỉ đang chờ thời điểm xuyên qua mây. Ánh dương không thuộc về một đóa hoa nào, nhưng mọi hoa đều nở nhờ nó — niềm vui của bạn không phụ thuộc vào ai, nhưng bạn có thể chia sẻ ánh sáng cùng nhau.'
  }},
  {id:20, emoji:'🔔', name:{zh:'审判',en:'Judgement',es:'El Juicio',fr:'Le Jugement',th:'การพิพากษา',vi:'Phán Xét'}, meaning:{
    zh:'重生与宽恕，灵魂被唤醒。这张牌在感情中出现，是对过去的一次深层审视与和解——你们的灵魂正在被召唤，去拥抱完整的真相、宽恕曾经的伤痛。逆位时，提示你可能还未准备好放下过去，但真正的自由始于对自己与对方的全然接纳，这是灵魂层面最深的治愈。审判不是惩罚，而是宇宙在问你：你愿意让自己自由吗？',
    en:'Rebirth and forgiveness — your soul is being called. In love, this card calls for a deep review and reconciliation with the past — your souls are summoned to embrace the full truth and forgive old wounds. Reversed, it suggests you may not yet be ready to release the past, but true freedom begins with complete acceptance of yourself and the other — this is the deepest healing at the soul level. Judgment is not punishment — it is the universe asking: are you willing to set yourself free?',
    es:'Renacimiento y perdón — tu alma está siendo llamada. En el amor, esta carta pide una revisión profunda y reconciliación con el pasado — sus almas son llamadas a abrazar la verdad completa y perdonar las heridas antiguas. Invertido, sugiere que puede que aún no esté listo para soltar el pasado, pero la verdadera libertad comienza con la aceptación completa de sí mismo y del otro — esta es la sanación más profunda a nivel del alma. El juicio no es castigo — es el universo preguntando: ¿estás dispuesto a liberarte?',
    fr:'Renaissance et pardon — votre âme est appelée. En amour, cette carte appelle à un examen approfondi et à une réconciliation avec le passé — vos âmes sont sommées d\'embrasser la vérité complète et de pardonner les vieilles blessures. Inversé, il suggère que vous n\'êtes peut-être pas encore prêt à libérer le passé, mais la véritable liberté commence par l\'acceptation complète de vous-même et de l\'autre — c\'est la guérison la plus profonde au niveau de l\'âme. Le jugement n\'est pas un châtiment — c\'est l\'univers qui demande : êtes-vous prêt à vous libérer ?',
    th:'การเกิดใหม่และการให้อภัย — วิญญาณของคุณกำลังถูกเรียก ในความรัก ไพ่นี้เรียกร้องให้ทบทวนและปรองดองกับอดีตอย่างลึกซึ้ง — วิญญาณของคุณถูกเรียกให้โอบกอดความจริงทั้งหมดและให้อภัยบาดแผลเก่า เมื่อกลับด้าน มันบอกว่าคุณอาจยังไม่พร้อมที่จะปล่อยวางอดีต แต่อิสรภาพแท้จริงเริ่มต้นจากการยอมรับตัวเองและอีกฝ่ายอย่างสมบูรณ์ — นี่คือการรักษาที่ลึกที่สุดในระดับวิญญาณ การพิพากษาไม่ใช่การลงโทษ — แต่เป็นจักรวาลที่ถามว่า: คุณยินดีที่จะปลดปล่อยตัวเองหรือไม่',
    vi:'Tái sinh và tha thứ — tâm hồn bạn đang được gọi. Trong tình yêu, lá bài này kêu gọi một sự nhìn lại và hòa giải sâu sắc với quá khứ — linh hồn bạn đang được triệu hồi để ôm trọn sự thật và tha thứ cho những vết thương xưa. Nếu xuất hiện ngược, có thể bạn chưa sẵn sàng buông bỏ quá khứ — nhưng tự do đích thực bắt đầu từ việc chấp nhận trọn vẹn bản thân và đối phương, đây là sự chữa lành sâu nhất ở tầng tâm linh. Phán xét không phải trừng phạt — mà là vũ trụ đang hỏi: bạn có sẵn sàng tự giải phóng chính mình?'
  }},
  {id:21, emoji:'🌍', name:{zh:'世界',en:'The World',es:'El Mundo',fr:'Le Monde',th:'โลก',vi:'Thế Giới'}, meaning:{
    zh:'完成与圆满，达成内在的和谐。这是感情修行之旅的终点——它意味着你们已经共同走过了一段完整的道路，并在这段旅程中找到了内在的和谐与满足。逆位时，提示你可能还未真正完成这段旅程，但请相信，你已经走过的每一步都算数，终点一直在前方等待。圆满不是没有遗憾，而是带着所有经历站成一个完整的圆——你的故事，正在成为一个传说。',
    en:'Completion and fulfillment — inner harmony achieved. This is the destination of love\'s journey — it means you have walked a full path together and found inner harmony and satisfaction along the way. Reversed, it suggests you may not have truly completed this journey yet, but trust: every step you\'ve taken counts, and the destination has always been waiting ahead. Fulfillment is not the absence of regret — it is standing as a complete circle with all your experiences. Your story is becoming a legend.',
    es:'Completitud y plenitud — armonía interior lograda. Este es el destino del viaje del amor — significa que han caminado un camino completo juntos y encontrado armonía y satisfacción interior en el camino. Invertido, sugiere que puede que aún no hayan completado verdaderamente este viaje, pero confíen: cada paso que han dado cuenta, y el destino siempre ha estado esperando más adelante. La plenitud no es la ausencia de arrepentimiento — es estar de pie como un círculo completo con todas sus experiencias. Su historia se está convirtiendo en una leyenda.',
    fr:'Accomplissement et plénitude — harmonie intérieure atteinte. C\'est la destination du voyage amoureux — cela signifie que vous avez parcouru un chemin complet ensemble et trouvé harmonie et satisfaction intérieure en chemin. Inversé, il suggère que vous n\'avez peut-être pas encore vraiment achevé ce voyage, mais faites confiance : chaque pas compte, et la destination vous attend toujours. L\'accomplissement n\'est pas l\'absence de regrets — c\'est se tenir en cercle complet avec toutes vos expériences. Votre histoire est en train de devenir une légende.',
    th:'ความสมบูรณ์และความเป็นหนึ่งเดียว — ความสามัคคีภายในบรรลุ นี่คือจุดหมายของการเดินทางแห่งความรัก — หมายถึงคุณได้เดินทางเสร็จสมบูรณ์ด้วยกันและพบความสามัคคีและความพึงพอใจภายในตลอดทาง เมื่อกลับด้าน มันบอกว่าคุณอาจยังไม่ได้จบการเดินทางนี้จริงๆ แต่จงเชื่อ: ทุกก้าวที่คุณก้าวมาล้วนมีค่า จุดหมายรอคุณอยู่ข้างหน้าเสมอ ความสมบูรณ์ไม่ใช่การไม่มีความเสียใจ — แต่คือการยืนเป็นวงกลมสมบูรณ์ด้วยประสบการณ์ทั้งหมด เรื่องราวของคุณกำลังกลายเป็นตำนาน',
    vi:'Hoàn thành và viên mãn — hài hòa bên trong đã đạt được. Đây là đích đến của hành trình tình yêu — bạn đã cùng nhau đi trọn một con đường và tìm thấy sự hài hòa, thỏa mãn bên trong. Nếu xuất hiện ngược, có thể bạn chưa thực sự hoàn thành hành trình — nhưng hãy tin, mỗi bước bạn đi đều có ý nghĩa, đích đến vẫn đang chờ phía trước. Viên mãn không phải là không có tiếc nuối — mà là mang theo mọi trải nghiệm đứng thành một vòng tròn trọn vẹn. Câu chuyện của bạn đang trở thành một huyền thoại.'
  }},
];

const ORIENT_SUFFIX: Record<string, (reversed: boolean) => string> = {
  zh: (r) => r ? '（逆位）' : '（正位）',
  en: (r) => r ? ' (Reversed)' : ' (Upright)',
  es: (r) => r ? ' (Invertido)' : ' (Normal)',
  fr: (r) => r ? ' (Inversé)' : ' (Droit)',
  th: (r) => r ? ' (กลับด้าน)' : ' (ตั้งตรง)',
  vi: (r) => r ? ' (Ngược)' : ' (Thuận)',
};

export function getTarot(d1: string, d2: string, lang: string = 'en'): TarotCard {
  const today = new Date().toISOString().slice(0, 10);
  let hash = 0;
  const sorted = [d1, d2].sort();
  const str = sorted[0] + '|' + sorted[1] + '|' + today;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash) + str.charCodeAt(i);
    hash |= 0;
  }
  const cardId = Math.abs(hash) % 22;
  const reversed = Math.floor(Math.abs(hash) / 22) % 2 === 1;
  const card = CARDS[cardId] || CARDS[0];
  const L = (lang in card.name) ? lang : 'en';
  return {
    id: card.id,
    name: card.name[L] || card.name.en,
    meaning: card.meaning[L] || card.meaning.en,
    emoji: card.emoji,
    orientation: (ORIENT_SUFFIX[L] || ORIENT_SUFFIX['en'])(reversed),
  };
}
