import React, { useEffect } from 'react';

// ── Styled HTML injection ──
const INSIGHT_STYLES = `
  .wealth-insight h1 {
    font-size: 20px;
    font-weight: 800;
    color: #D4AF37;
    margin: 24px 0 12px;
    letter-spacing: -0.5px;
  }
  .wealth-insight h2 {
    font-size: 17px;
    font-weight: 700;
    color: #E8E4D9;
    margin: 20px 0 10px;
    padding-bottom: 6px;
    border-bottom: 1px solid rgba(212, 175, 55, 0.2);
  }
  .wealth-insight h3 {
    font-size: 15px;
    font-weight: 700;
    color: #81D8D0;
    margin: 16px 0 8px;
  }
  .wealth-insight p {
    font-size: 13px;
    line-height: 1.8;
    color: #C0BCB0;
    margin: 8px 0;
  }
  .wealth-insight strong {
    color: #E8E4D9;
    font-weight: 700;
  }
  .wealth-insight .red-light {
    color: #E05C5C;
    font-weight: 700;
  }
  .wealth-insight .green-light {
    color: #5CB85C;
    font-weight: 700;
  }
  .wealth-insight ul, .wealth-insight ol {
    margin: 8px 0;
    padding-left: 20px;
  }
  .wealth-insight li {
    font-size: 13px;
    line-height: 1.9;
    color: #C0BCB0;
    margin: 4px 0;
    word-break: break-word;
    overflow-wrap: break-word;
  }
  .wealth-insight blockquote {
    border-left: 3px solid #D4AF37;
    padding-left: 12px;
    margin: 12px 0;
    color: #8B8778;
    font-style: italic;
    word-break: break-word;
    overflow-wrap: break-word;
  }
  .wealth-insight .section-card {
    background: linear-gradient(135deg, #0e0e1a 0%, #12121f 100%);
    border: 1px solid rgba(212, 175, 55, 0.25);
    border-radius: 12px;
    padding: 16px;
    margin: 16px 0;
    transition: all 0.3s ease;
  }
  .wealth-insight .section-card:hover {
    border-color: rgba(212, 175, 55, 0.5);
    box-shadow: 0 4px 16px rgba(212, 175, 55, 0.15);
  }
`;

// ── Component ──
const WealthInsightCard: React.FC<{ insight: string }> = ({ insight }) => {
  useEffect(() => {
    // Inject styles on mount
    const styleId = 'wealth-insight-styles';
    if (!document.getElementById(styleId)) {
      const style = document.createElement('style');
      style.id = styleId;
      style.textContent = INSIGHT_STYLES;
      document.head.appendChild(style);
    }
  }, []);

  if (!insight) return null;

  return (
    <div
      className="wealth-insight"
      style={{
        padding: '20px 0',
        animation: 'fadeIn 0.6s ease-out',
      }}
    >
      {/* Render HTML safely (insight is generated by our backend, not user input) */}
      {/* 🛡️ 6国语言防弹装甲：break-word + overflow-wrap + white-space 防止排版车祸 */}
      <div
        dangerouslySetInnerHTML={{ __html: insight }}
        style={{
          overflow: 'hidden',
          wordBreak: 'break-word',
          overflowWrap: 'break-word',
          whiteSpace: 'pre-wrap',
        }}
      />
    </div>
  );
};

export default WealthInsightCard;
